Repository woowa-techcamp-2022/web-fleamarket-07, pull requests merged in 2022-08, with the labels that each got.

#2 nest entity, module, service, 테이블 관계 정의
  common/index.ts
  common/types/product/EProductStatus.ts
  common/types/product/TProduct.ts
  common/types/product/index.ts
  server/src/app.module.ts
  server/src/config/database/config.service.ts
  server/src/domain/category/category.controller.ts
  server/src/domain/category/category.module.ts
  server/src/domain/category/category.service.ts
  server/src/domain/category/entities/category.entity.ts
  server/src/domain/chat/chat.controller.ts
  server/src/domain/chat/chat.module.ts
  server/src/domain/chat/chat.service.ts
  server/src/domain/chat/entities/chat.entity.ts
  server/src/domain/image/entities/image.entity.ts
  server/src/domain/image/image.controller.ts
  server/src/domain/image/image.module.ts
  server/src/domain/image/image.service.ts
  server/src/domain/like/entities/like.entity.ts
  server/src/domain/like/like.module.ts
  server/src/domain/like/like.service.ts
  server/src/domain/location/entities/location.entity.ts
  server/src/domain/location/location.controller.ts
  server/src/domain/location/location.module.ts
  server/src/domain/location/location.service.ts
  server/src/domain/product/entities/product.entity.ts
  server/src/domain/product/product.controller.ts
  server/src/domain/product/product.module.ts
  server/src/domain/product/product.service.ts
  server/src/domain/room/entities/room.entity.ts
  server/src/domain/room/room.controller.ts
  server/src/domain/room/room.module.ts
  server/src/domain/room/room.service.ts
  server/src/domain/user/entities/user.entity.ts
  server/src/domain/user/user.controller.ts
  server/src/domain/user/user.module.ts
  server/src/domain/user/user.service.ts
Labels: backend, feature

#7 Feat/4/category api
  common/types/TCategory.ts
Labels: backend, feature, frontend

#9 feat/8/common-path
  common/index.ts
  common/types/product/EProductStatus.ts
  common/types/product/TProductDetail.ts
  common/types/product/TProductUpdate.ts
  common/types/product/index.ts
  server/src/domain/product/entities/product.entity.ts
Labels: backend, feature

#13 Feat/10/router
  client/package.json
  client/src/App.tsx
  client/src/GlobalStyles.tsx
  client/src/pages/Category.tsx
  client/src/pages/LocationEdit.tsx
  client/src/pages/Main.tsx
  client/src/pages/Menu.tsx
  client/src/pages/NewProduct.tsx
  client/src/pages/NotFound.tsx
  client/src/pages/ProductDetail.tsx
  client/src/pages/SignIn.tsx
  client/src/pages/SignUp.tsx
  client/src/pages/index.ts
  client/tsconfig.path.json
  yarn.lock
Labels: feature, frontend

#15 Feat/14/top bar
  client/package.json
  client/src/components/moecules/TopBar.tsx
  yarn.lock
Labels: feature, frontend

#17 Feat/11/oauth
  client/src/constants/envs.ts
  server/package.json
  server/src/config/env.validation.ts
  server/src/domain/location/entities/location.entity.ts
  server/src/domain/location/location.service.ts
  server/src/domain/user/entities/user.entity.ts
  server/src/domain/user/user.controller.ts
  server/src/domain/user/user.module.ts
  server/src/domain/user/user.service.ts
  yarn.lock
Labels: backend, feature, setting

#19 style : 테마 색상을 노란색으로 변경
  client/src/constants/style.ts
  client/src/constants/theme.ts
Labels: frontend, style

#25 Feat/22/category component&page
  client/src/components/molecules/Heart.tsx
  client/src/components/molecules/TopBar.tsx
  client/src/components/organisms/CategoryItem.tsx
  client/src/components/organisms/ProductItem.tsx
  client/src/pages/Category.tsx
Labels: feature, frontend

#23 Feat/20/jwt
  server/package.json
  server/src/config/env.validation.ts
  server/src/domain/auth/auth.guard.ts
  server/src/domain/auth/auth.module.ts
  server/src/domain/auth/auth.service.ts
  server/src/domain/user/user.controller.ts
  server/src/domain/user/user.module.ts
  server/src/domain/user/user.service.ts
  yarn.lock
Labels: backend, setting

#27 feat : MenuHeader 컴포넌트 구현
  client/src/components/molecules/MenuHeader.tsx
Labels: feature, frontend, style

#29 Feat/28/main page
  client/src/App.tsx
  client/src/components/organisms/CategoryItem.tsx
  client/src/components/organisms/ProductItem.tsx
  client/src/pages/Main.tsx
Labels: feature, frontend, style

#32 Feat/31/dropdown
  client/src/components/molecules/Dropdown.tsx
  client/src/components/organisms/MenuHeader.tsx
Labels: feature, frontend, style

#30 Feat/24/route animate
  client/src/App.tsx
  client/src/GlobalStyles.tsx
  client/src/components/Animator.tsx
  client/src/constants/slideStyle.ts
  client/src/hooks/useAnimator.tsx
  client/src/hooks/useStack.ts
  client/src/index.tsx
  client/src/pages/Main.tsx
  client/tsconfig.path.json
Labels: feature, frontend, style

#36 Feat/33/multer image
  server/package.json
  server/src/config/env.validation.ts
  server/src/domain/image/image.file.service.ts
  server/src/domain/image/image.module.ts
  yarn.lock
Labels: backend, feature, setting

#42 Feat/37/product read all
  common/index.ts
  common/types/TCategory.ts
  common/types/TImage.ts
  common/types/TLocation.ts
  common/types/TUser.ts
  common/types/product/TProduct.ts
  common/types/product/TProductAllQuery.ts
  common/types/product/TProductCreate.ts
  common/types/product/TProductDetail.ts
  common/types/product/TProductSummary.ts
  common/types/product/TProductUpdate.ts
  common/types/product/index.ts
  server/src/domain/product/entities/product.entity.ts
  server/src/domain/product/product.controller.ts
  server/src/domain/product/product.service.ts
Labels: backend, feature

#45 Feat/44/loading indicator
  client/src/components/atoms/Loading.tsx
  client/src/components/organisms/ProductItem.tsx
Labels: feature, frontend

#47 Feat/41/login authentication
  client/package.json
  client/src/apis/user.ts
  client/src/apis/util/index.ts
  client/src/apis/util/interceptor.ts
  client/src/utils/cookie.ts
  client/tsconfig.path.json
  common/index.ts
  common/types/product/TProduct.ts
  common/types/product/TProductDetail.ts
  common/types/user/TUser.ts
  common/types/user/TUserGithub.ts
  common/types/user/index.ts
  server/src/domain/auth/auth.service.ts
  server/src/domain/user/entities/user.entity.ts
  server/src/domain/user/user.controller.ts
  server/src/domain/user/user.service.ts
  yarn.lock
Labels: backend, feature, frontend

#38 Feat/34/locatin edit page
  client/src/components/molecules/LocationModal.tsx
  client/src/components/organisms/LocationContent.tsx
  client/src/pages/LocationEdit.tsx
Labels: feature, frontend, style

#40 Feat/39/login page
  client/public/baemin.png
  client/public/github.svg
  client/src/pages/SignIn.tsx
Labels: feature, frontend, style

#50 Feat/48/auth router
  client/src/App.tsx
  client/src/components/Verification.tsx
  client/src/components/molecules/LogOut.tsx
  client/src/hooks/useAuth.ts
  client/src/pages/SignIn.tsx
  client/src/stores/AuthRecoil.ts
  client/tsconfig.path.json
Labels: feature, frontend, style, setting

#49 Feat/43/main product all
  client/public/defaultImage.png
  client/public/empty.png
  client/public/error.png
  client/src/apis/product.ts
  client/src/apis/util/index.ts
  client/src/components/atoms/Guide.tsx
  client/src/components/molecules/ImageBox.tsx
  client/src/components/organisms/ImageLarge.png
  client/src/components/organisms/MainLayout.tsx
  client/src/components/organisms/MenuHeader.tsx
  client/src/components/organisms/ProductItem.tsx
  client/src/constants/envs.ts
  client/src/constants/style.ts
  client/src/pages/Main.tsx
  client/src/utils/time.ts
Labels: feature, frontend, style

#54 Feat/51/logout
  client/src/apis/user.ts
  client/src/components/molecules/LogOut.tsx
  client/src/components/organisms/MenuHeader.tsx
  client/src/pages/SignIn.tsx
  server/src/domain/user/user.controller.ts
  server/src/domain/user/user.service.ts
  server/src/main.ts
Labels: backend, feature, frontend

#53 Feat/52/product detail
  client/src/components/organisms/ProductItem.tsx
  common/types/product/TProductDetail.ts
  common/types/product/TProductSummary.ts
  server/src/domain/product/product.controller.ts
  server/src/domain/product/product.service.ts
Labels: backend, feature

#60 Feat/55/product detail
  client/package.json
  client/src/App.tsx
  client/src/apis/product.ts
  client/src/components/Animator.tsx
  client/src/components/molecules/Dropdown.tsx
  client/src/components/molecules/ImageBox.tsx
  client/src/components/molecules/TopBar.tsx
  client/src/components/organisms/MenuHeader.tsx
  client/src/components/organisms/ProductContent.tsx
  client/src/components/organisms/ProductItem.tsx
  client/src/constants/style.ts
  client/src/pages/ProductDetail.tsx
  common/types/product/TProductDetail.ts
  yarn.lock
Labels: feature, frontend

#59 Feat/58/sale list
  client/package.json
  client/src/apis/product.ts
  client/src/components/molecules/Dropdown.tsx
  client/src/components/molecules/TopBar.tsx
  client/src/components/organisms/ProductItem.tsx
  client/src/components/organisms/SaleList.tsx
  client/src/components/organisms/Tap.tsx
  client/src/pages/Menu.tsx
  server/src/domain/product/product.controller.ts
  server/src/domain/product/product.module.ts
  server/src/domain/product/product.service.ts
  yarn.lock
Labels: backend, feature, frontend

#63 Bug/62/yarn
  client/package.json
  client/src/apis/product.ts
  yarn.lock
Labels: bug

#67 Feat/66/chat list
  client/src/components/molecules/RoomItem.tsx
  client/src/components/organisms/RoomList.tsx
  client/src/components/organisms/Tap.tsx
Labels: feature, frontend, style

#70 Feat/69/product create api
  server/src/domain/image/image.controller.ts
  server/src/domain/image/image.service.ts
  server/src/domain/product/product.controller.ts
  server/src/domain/product/product.module.ts
  server/src/domain/product/product.service.ts
Labels: backend, feature

#71 Feat/61/chat socket
  client/package.json
  client/src/App.tsx
  client/src/components/molecules/ChatInput.tsx
  client/src/components/molecules/ChatItem.tsx
  client/src/components/organisms/ChatList.tsx
  client/src/constants/envs.ts
  client/src/hooks/useChat.tsx
  client/src/index.tsx
  client/src/pages/Chat.tsx
  client/src/pages/ProductDetail.tsx
  client/src/sockets/chat.ts
  client/src/sockets/index.ts
  client/src/utils/time.ts
  client/tsconfig.path.json
  common/index.ts
  common/types/TRoom.ts
  common/types/chat/SocketDto.ts
  common/types/chat/SocketEvent.ts
  common/types/chat/TChat.ts
  common/types/chat/index.ts
  server/package.json
  server/src/app.module.ts
  server/src/config/env.validation.ts
  server/src/domain/auth/auth.data.guard.ts
  server/src/domain/auth/auth.service.ts
  server/src/domain/auth/auth.socket.guard.ts
  server/src/domain/chat/chat.module.ts
  server/src/domain/chat/chat.service.ts
  server/src/domain/chat/chat.socket.service.ts
  server/src/domain/room/room.service.ts
  server/src/domain/socket/socket.gateway.ts
  server/src/domain/socket/socket.module.ts
  server/src/main.ts
  yarn.lock
Labels: backend, feature, frontend

#73 Feat/72/roomlist socket
  client/src/App.tsx
  client/src/components/Animator.tsx
  client/src/components/molecules/ChatInput.tsx
  client/src/components/molecules/RoomItem.tsx
  client/src/components/organisms/RoomList.tsx
  client/src/components/organisms/Tap.tsx
  client/src/hooks/useChat.ts
  client/src/hooks/useRoom.ts
  client/src/pages/Chat.tsx
  client/src/pages/Menu.tsx
  client/src/pages/ProductDetail.tsx
  client/src/sockets/index.ts
  client/src/sockets/room.ts
  common/index.ts
  common/types/chat/SocketDto.ts
  common/types/chat/TChat.ts
  common/types/room/SocketDto.ts
  common/types/room/SocketEvent.ts
  common/types/room/TRoom.ts
  common/types/room/index.ts
  server/src/domain/chat/chat.module.ts
  server/src/domain/product/entities/product.entity.ts
  server/src/domain/room/entities/room.entity.ts
  server/src/domain/room/room.controller.ts
  server/src/domain/room/room.module.ts
  server/src/domain/room/room.service.ts
  server/src/domain/room/room.socket.service.ts
  server/src/domain/socket/socket.gateway.ts
  server/src/domain/socket/socket.module.ts
  yarn.lock
Labels: backend, feature, frontend

#75 Feat/68/new product create
  client/src/apis/product.ts
  client/src/components/organisms/ImageUpload.tsx
  client/src/components/organisms/Tap.tsx
  client/src/constants/categoryList.ts
  client/src/pages/Category.tsx
  client/src/pages/NewProduct.tsx
Labels: feature, frontend, refact

#79 Feat/78/select category
  client/src/apis/product.ts
  client/src/components/organisms/CategoryItem.tsx
  client/src/constants/categoryList.ts
  client/src/pages/Category.tsx
  client/src/pages/Main.tsx
  client/src/stores/ActionInfoRecoil.ts
Labels: feature, frontend

#81 Feat/80/select location
  client/src/App.tsx
  client/src/apis/user.ts
  client/src/components/molecules/LocationModal.tsx
  client/src/components/organisms/LocationContent.tsx
  client/src/components/organisms/MenuHeader.tsx
  client/src/stores/ActionInfoRecoil.ts
  common/index.ts
  common/types/TLocation.ts
  server/src/domain/user/user.controller.ts
  server/src/domain/user/user.service.ts
Labels: feature, frontend

#82 Feat/74/chat detail
  client/src/apis/product.ts
  client/src/components/Animator.tsx
  client/src/components/molecules/ChatAvatar.tsx
  client/src/components/molecules/ChatController.tsx
  client/src/components/molecules/ChatInput.tsx
  client/src/components/molecules/ChatItem.tsx
  client/src/components/molecules/SwipeTab.tsx
  client/src/components/organisms/ChatList.tsx
  client/src/components/organisms/ChatRoomInfo.tsx
  client/src/components/organisms/LikeList.tsx
  client/src/components/organisms/RoomList.tsx
  client/src/components/organisms/SaleList.tsx
  client/src/components/organisms/Tap.tsx
  client/src/hooks/useAnimator.tsx
  client/src/hooks/useChat.ts
  client/src/hooks/useRoom.ts
  client/src/hooks/useStack.ts
  client/src/pages/Chat.tsx
  client/src/pages/Menu.tsx
  client/src/pages/SignIn.tsx
  client/src/sockets/chat.ts
  client/src/sockets/room.ts
  client/src/stores/Chat.ts
  client/src/utils/cookie.ts
  client/src/utils/time.ts
  common/index.ts
  common/types/TLocation.ts
  server/src/domain/chat/chat.socket.service.ts
  server/src/domain/product/product.service.ts
  server/src/domain/room/room.service.ts
Labels: backend, feature, frontend

#85 bug : 아이콘 클릭 시, 상품 클릭 이벤트 발생 해결
  client/src/components/molecules/ImageBox.tsx
  client/src/components/organisms/ProductItem.tsx
  client/src/components/organisms/SaleList.tsx
  client/src/constants/dropDownList.ts
  client/src/pages/Main.tsx
Labels: frontend, refact

#87 Feat/83/location create
  client/src/App.tsx
  client/src/apis/location.ts
  client/src/components/molecules/LocationModal.tsx
  client/src/components/organisms/ImageUpload.tsx
  client/src/components/organisms/LikeList.tsx
  client/src/components/organisms/LocationContent.tsx
  client/src/components/organisms/MainLayout.tsx
  client/src/components/organisms/MenuHeader.tsx
  client/src/components/organisms/SaleList.tsx
  client/src/constants/slideStyle.ts
  client/src/hooks/useAnimator.tsx
  client/src/pages/Main.tsx
  client/src/pages/NewProduct.tsx
  client/src/pages/ProductDetail.tsx
  common/index.ts
  common/types/location/TLocation.ts
  common/types/location/TLocationCreate.ts
  common/types/location/TLocationDelete.ts
  common/types/location/index.ts
  common/types/product/TProduct.ts
  common/types/product/TProductAllQuery.ts
  common/types/product/TProductDetail.ts
  common/types/user/TUser.ts
  common/types/user/TUserGithub.ts
  server/src/domain/location/location.controller.ts
  server/src/domain/location/location.module.ts
  server/src/domain/location/location.service.ts
  server/src/domain/product/entities/product.entity.ts
  server/src/domain/user/user.module.ts
  server/src/domain/user/user.service.ts
Labels: backend, feature, frontend, style

#89 Feat/86/product delete
  client/src/apis/product.ts
  client/src/apis/util/interceptor.ts
  client/src/components/molecules/Dropdown.tsx
  client/src/components/molecules/TopBar.tsx
  client/src/components/organisms/SaleList.tsx
  client/src/pages/Main.tsx
  client/src/pages/ProductDetail.tsx
  server/src/domain/product/product.controller.ts
  server/src/domain/product/product.service.ts
Labels: backend, feature, frontend

#90 Feat/88/like api
  client/src/App.tsx
  client/src/apis/product.ts
  client/src/components/organisms/LikeList.tsx
  client/src/pages/Main.tsx
  client/src/pages/ProductDetail.tsx
  server/src/domain/like/like.service.ts
  server/src/domain/product/product.controller.ts
  server/src/domain/product/product.module.ts
  server/src/domain/product/product.service.ts
Labels: backend, feature, frontend

#92 Bug/91/before presentation
  client/src/components/Verification.tsx
  client/src/components/molecules/SwipeTab.tsx
  client/src/components/organisms/CategoryItem.tsx
  client/src/components/organisms/MenuHeader.tsx
  client/src/pages/NewProduct.tsx
  client/src/pages/SignIn.tsx
  server/src/config/database/config.service.ts
Labels: bug, backend, frontend

#97 feat/96/hit count
  server/src/domain/product/product.controller.ts
  server/src/domain/product/product.service.ts
Labels: backend, feature

#95 Bug/94/self like inquiry
  client/public/favicon.ico
  client/src/pages/NewProduct.tsx
  client/src/pages/ProductDetail.tsx
Labels: feature, frontend

#99 Feat/93/room create
  client/src/App.tsx
  client/src/components/molecules/ChatController.tsx
  client/src/components/molecules/RoomItem.tsx
  client/src/components/organisms/ChatList.tsx
  client/src/hooks/useChat.ts
  client/src/pages/Chat.tsx
  client/src/pages/SignIn.tsx
  client/src/sockets/chat.ts
  client/src/sockets/room.ts
  common/types/chat/SocketDto.ts
  server/src/domain/chat/chat.module.ts
  server/src/domain/chat/chat.socket.service.ts
  server/src/domain/product/product.service.ts
  server/src/domain/room/room.service.ts
Labels: backend, feature, frontend

#103 feat/101/readme
  README.md
Labels: docs

#104 bug : 상품 채팅 들어가지지 않던 버그 수정
  client/src/pages/ProductDetail.tsx
Labels: bug

#106 docs/105/readme
  README.md
Labels: docs
